- hosts: webservers
  become: true
  vars_files:
    - vars/default.yml

  tasks:
  # Update package repositories
    - name: "Update Repository cache"
      apt:
        update_cache: yes
        force_apt_get: true

    - name: "Install pip"
      apt:
        name: python3-pip
        state: present
