############################################################################
# Configure a LAMP server
############################################################################

# NGINX conf template go de
# Script to run docker operations [pull, compose, run]

# sudo docker stop altschool-project
# sudo docker rm altschool-project
# sudo docker rmi -f demarauder/altschool-project:latest
# sudo docker compose pull
# sudo docker compose up -d --build altschool-project
# sudo docker system prune -af && exit'

- hosts: replica
  become: true
  vars_files:
    - vars/default.yml

  tasks:
  # Update repositories
  - name: Update repository cache
    package:
      update_cache: true

  # Install Server requirements
  - name: Install Server requirements
    package:
      name: [ 'nginx' ]
      state: present

  # Install docker

  # Pull project from dockerhub

  # Start app with docker

  # Enable site with nginx
  - name: Unlink default nginx conf
    shell: unlink /etc/nginx/sites-enabled/default
    notify: Reload Apache

  - name: Link altschool-project nginx conf
    shell: "ln -s /etc/nginx/sites-available/{{ project_conf }} /etc/nginx/sites-enabled/{{ project_conf }}" 
    notify: Reload Apache

  - name: Reload NGINX
    service:
      name: nginx
      state: reloaded
