- name: Kube Master setup
  hosts: all
  become: yes
  tasks:
    - name: Set environment variables
      shell: |
        IPADDR="$(ip --json a s | jq -r '.[] | if .ifname == "eth0" then .addr_info[] | if .family == "inet" then .local else empty end else empty end')"
        echo $IPADDR
        NODENAME=$(hostname -s)
        echo $NODENAME
        POD_CIDR="192.168.0.0/16"
        echo $POD_CIDR
        kubeadm init --apiserver-advertise-address=$IPADDR  --apiserver-cert-extra-sans=$IPADDR  --pod-network-cidr=$POD_CIDR --node-name $NODENAME --ignore-preflight-errors Swap,Mem,NumCPU
        
    - name: Install helm
      shell: |
        curl -LO https://get.helm.sh/helm-v3.11.1-linux-amd64.tar.gz
        tar -zxvf helm-v3.11.1-linux-amd64.tar.gz
        mv linux-amd64/helm /usr/local/bin/helm
      args:
        executable: /bin/bash
      register: helm_install_output

    - debug: var=helm_install_output

    - name: Install cert-manager with Helm
      shell: |
        helm repo add jetstack https://charts.jetstack.io
        helm repo update
        helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.11.0 --set installCRDs=true

      args:
        executable: /bin/bash
      register: helm_install_cert-manager

    - debug: var=helm_install_cert-manager

    - name: Install ingress-nginx with Helm
      shell: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx 
        helm repo update
        helm install ingress-nginx ingress-nginx/ingress-nginx
      args:
        executable: /bin/bash
      register: helm_install_ingress-nginx

    - debug: var=helm_install_ingress-nginx

    - name: Create token
      shell: kubeadm token create --print-join-command
      args:
        executable: /bin/bash
      register: shell_output

    - debug: var=shell_output

    - name: Set path to kube config
      shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        echo "export KUBECONFIG=/etc/kubernetes/admin.conf" >>~/.bashrc
        echo "export KUBECONFIG=/etc/kubernetes/admin.conf" >>/home/ubuntu/.bashrc
        kubectl apply -f https://raw.githubusercontent.com/techiescamp/kubeadm-scripts/main/manifests/metrics-server.yaml
